### ISSUE TITLE
Downloading Channel list takes a very long time, then fails

### ISSUE THREAD

**Issue by seangates** [TeamCodeStream/CodeStream#10]
On first start, the new CodeStream setup with Slack tries to download my channel list. Consequently, it's either trying to download just the channels I belong to, or trying to download over ~1500~ 3900 public channels from our workspace (yes, we have a large org).

This is all I saw this for 10 minutes:

![image](https://user-images.githubusercontent.com/105656/47049478-a9c01600-d15a-11e8-8416-3ac383b0daa0.png)

Then, it went back to this (my email removed, hence the error):

![image](https://user-images.githubusercontent.com/105656/47049564-e2f88600-d15a-11e8-9154-fda7889391fb.png)

**Comment by eamodio** [comment]
@seangates Can you try again with v0.20 in the marketplace -- it should resolve this issue.

**Comment by seangates** [comment]
So, it's still not working for me.

**Comment by planteater** [comment]
@seangates - If you have a sec, please give the latest version (0.22.1) a shot and let us know if you're still seeing any issues. Thanks!

**Comment by seangates** [comment]
@planteater Still not working. Should I send you some debugging logs?

**Comment by planteater** [comment]
@seangates - Logs would be great! Here are the details:

- Make sure you have the latest CodeStream extension for VS Code, which is version 0.22.1.
- In your VS Code user settings (see gear menu at bottom left of VSC), search for CodeStream and change the Trace Level setting to "Debug".
- Reload VS Code by going to the VS Code command palette (Cmd + Shift + P) and then searching for Reload.
- Go ahead and try to sign into CodeStream again.
- If you run into any issues, open the VS Code Output view with Cmd + Shift + U and select "CodeStream" from the dropdown at the top-right of that pane.
- Copy everything there and paste it into a text file to send to me.
- Change the dropdown selection to "CodeStream (Agent)" and grab that output as well.

Thanks! We really appreciate your patience here and willingness to help.

**Comment by seangates** [comment]
So, I've waited for about 10 minutes for the logging to complete, and it finally did:

![image](https://user-images.githubusercontent.com/105656/48219347-83e8f400-e349-11e8-9758-e0e3b23b3b36.png)

But, still no channels show up.

**Comment by eamodio** [comment]
@seangates This should be largely resolved in CodeStream v0.30. Please let us know -- thanks!

**Comment by seangates** [comment]
IT WORKS! Thank you for getting this all ironed out. I hope my feedback (and gobs of logs) were helpful.

Now ... to fix threading ...
