### ISSUE TITLE
PHPStorm cant be opened in Linux Mint 19 with Slack Link "Open in IDE"

### ISSUE THREAD

**Issue by Bigfischi85** [TeamCodeStream/CodeStream#121]
**Describe the bug**
When I click on the link of a comment in Slack "Open in IDE", a Chrome Tab opens with another Link "Open IDE". After choosing "Open in PHPStorm" the attached jpeg error message of Jetbrains Toolbox appears.

**System Info**
 - Version of the CodeStream extension: 4.0.1+18
 - Linux Mint 19
 - PHPStorm 2019.2.3

**Log Files**
![Jetbrains Error](https://user-images.githubusercontent.com/18024031/66319117-d5647f00-e91c-11e9-9e03-8004df6b4c7d.jpeg)

**Comment by planteater** [comment]
Thanks for the heads up @Bigfischi85 ! This should be fixed now.

**Comment by Bigfischi85** [comment]
> Thanks for the heads up @Bigfischi85 ! This should be fixed now.

Thank you @planteater :) i just wait for an update of the PHPStorm Extension?

**Comment by planteater** [comment]
@Bigfischi85 - No need, as the fix was on our backend. I would just restart your IDE to be safe.

**Comment by Bigfischi85** [comment]
> @Bigfischi85 - No need, as the fix was on our backend. I would just restart your IDE to be safe.

Still the same error, also after reboot :(

![Jetbrains Error 2](https://user-images.githubusercontent.com/18024031/66368565-ff5b8700-e998-11e9-897e-ec2c8b7b06e1.jpeg)

**Comment by planteater** [comment]
Well, turns out that fixes are far more effective when they actually get deployed.

Sorry about that! Can you try again now?

**Comment by Bigfischi85** [comment]
> Well, turns out that fixes are far more effective when they actually get deployed.
> 
> Sorry about that! Can you try again now?

Great, it works now :)
